<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Asisste.ApiData</RootNamespace>
    <AssemblyName>Asisste.ApiData</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\2-Application\Asisste.Services\Asisste.Services.csproj" />
    <ProjectReference Include="..\..\1-Core\Asisste.Domain\Asisste.Domain.csproj" />
  </ItemGroup>

</Project>